// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/cloud/speech/v2/cloud_speech_minimal.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Google_Cloud_Speech_V2_AutoDetectDecodingConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Google_Cloud_Speech_V2_ExplicitDecodingConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var encoding: Google_Cloud_Speech_V2_ExplicitDecodingConfig.AudioEncoding = .unspecified

  var sampleRateHertz: Int32 = 0

  var audioChannelCount: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum AudioEncoding: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case linear16 // = 1
    case mulaw // = 2
    case alaw // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .linear16
      case 2: self = .mulaw
      case 3: self = .alaw
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .linear16: return 1
      case .mulaw: return 2
      case .alaw: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Google_Cloud_Speech_V2_ExplicitDecodingConfig.AudioEncoding] = [
      .unspecified,
      .linear16,
      .mulaw,
      .alaw,
    ]

  }

  init() {}
}

struct Google_Cloud_Speech_V2_RecognitionConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var decodingConfig: Google_Cloud_Speech_V2_RecognitionConfig.OneOf_DecodingConfig? = nil

  var autoDecodingConfig: Google_Cloud_Speech_V2_AutoDetectDecodingConfig {
    get {
      if case .autoDecodingConfig(let v)? = decodingConfig {return v}
      return Google_Cloud_Speech_V2_AutoDetectDecodingConfig()
    }
    set {decodingConfig = .autoDecodingConfig(newValue)}
  }

  var explicitDecodingConfig: Google_Cloud_Speech_V2_ExplicitDecodingConfig {
    get {
      if case .explicitDecodingConfig(let v)? = decodingConfig {return v}
      return Google_Cloud_Speech_V2_ExplicitDecodingConfig()
    }
    set {decodingConfig = .explicitDecodingConfig(newValue)}
  }

  var model: String = String()

  var languageCodes: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_DecodingConfig: Equatable, Sendable {
    case autoDecodingConfig(Google_Cloud_Speech_V2_AutoDetectDecodingConfig)
    case explicitDecodingConfig(Google_Cloud_Speech_V2_ExplicitDecodingConfig)

  }

  init() {}
}

struct Google_Cloud_Speech_V2_StreamingRecognitionFeatures: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var enableVoiceActivityEvents: Bool = false

  var interimResults: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Google_Cloud_Speech_V2_StreamingRecognitionConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var config: Google_Cloud_Speech_V2_RecognitionConfig {
    get {_config ?? Google_Cloud_Speech_V2_RecognitionConfig()}
    set {_config = newValue}
  }
  /// Returns true if `config` has been explicitly set.
  var hasConfig: Bool {self._config != nil}
  /// Clears the value of `config`. Subsequent reads from it will return its default value.
  mutating func clearConfig() {self._config = nil}

  var streamingFeatures: Google_Cloud_Speech_V2_StreamingRecognitionFeatures {
    get {_streamingFeatures ?? Google_Cloud_Speech_V2_StreamingRecognitionFeatures()}
    set {_streamingFeatures = newValue}
  }
  /// Returns true if `streamingFeatures` has been explicitly set.
  var hasStreamingFeatures: Bool {self._streamingFeatures != nil}
  /// Clears the value of `streamingFeatures`. Subsequent reads from it will return its default value.
  mutating func clearStreamingFeatures() {self._streamingFeatures = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _config: Google_Cloud_Speech_V2_RecognitionConfig? = nil
  fileprivate var _streamingFeatures: Google_Cloud_Speech_V2_StreamingRecognitionFeatures? = nil
}

struct Google_Cloud_Speech_V2_StreamingRecognizeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var recognizer: String = String()

  var streamingRequest: Google_Cloud_Speech_V2_StreamingRecognizeRequest.OneOf_StreamingRequest? = nil

  var streamingConfig: Google_Cloud_Speech_V2_StreamingRecognitionConfig {
    get {
      if case .streamingConfig(let v)? = streamingRequest {return v}
      return Google_Cloud_Speech_V2_StreamingRecognitionConfig()
    }
    set {streamingRequest = .streamingConfig(newValue)}
  }

  var audio: Data {
    get {
      if case .audio(let v)? = streamingRequest {return v}
      return Data()
    }
    set {streamingRequest = .audio(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_StreamingRequest: Equatable, Sendable {
    case streamingConfig(Google_Cloud_Speech_V2_StreamingRecognitionConfig)
    case audio(Data)

  }

  init() {}
}

struct Google_Cloud_Speech_V2_SpeechRecognitionAlternative: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var transcript: String = String()

  var confidence: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Google_Cloud_Speech_V2_StreamingRecognitionResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var alternatives: [Google_Cloud_Speech_V2_SpeechRecognitionAlternative] = []

  var isFinal: Bool = false

  var stability: Float = 0

  var channelTag: Int32 = 0

  var languageCode: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Google_Cloud_Speech_V2_StreamingRecognizeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var results: [Google_Cloud_Speech_V2_StreamingRecognitionResult] = []

  var speechEventType: Google_Cloud_Speech_V2_StreamingRecognizeResponse.SpeechEventType = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum SpeechEventType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case endOfSingleUtterance // = 1
    case speechActivityBegin // = 2
    case speechActivityEnd // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .endOfSingleUtterance
      case 2: self = .speechActivityBegin
      case 3: self = .speechActivityEnd
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .endOfSingleUtterance: return 1
      case .speechActivityBegin: return 2
      case .speechActivityEnd: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Google_Cloud_Speech_V2_StreamingRecognizeResponse.SpeechEventType] = [
      .unspecified,
      .endOfSingleUtterance,
      .speechActivityBegin,
      .speechActivityEnd,
    ]

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.cloud.speech.v2"

extension Google_Cloud_Speech_V2_AutoDetectDecodingConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AutoDetectDecodingConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_AutoDetectDecodingConfig, rhs: Google_Cloud_Speech_V2_AutoDetectDecodingConfig) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_ExplicitDecodingConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ExplicitDecodingConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}encoding\0\u{3}sample_rate_hertz\0\u{3}audio_channel_count\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.encoding) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.sampleRateHertz) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.audioChannelCount) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.encoding != .unspecified {
      try visitor.visitSingularEnumField(value: self.encoding, fieldNumber: 1)
    }
    if self.sampleRateHertz != 0 {
      try visitor.visitSingularInt32Field(value: self.sampleRateHertz, fieldNumber: 2)
    }
    if self.audioChannelCount != 0 {
      try visitor.visitSingularInt32Field(value: self.audioChannelCount, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_ExplicitDecodingConfig, rhs: Google_Cloud_Speech_V2_ExplicitDecodingConfig) -> Bool {
    if lhs.encoding != rhs.encoding {return false}
    if lhs.sampleRateHertz != rhs.sampleRateHertz {return false}
    if lhs.audioChannelCount != rhs.audioChannelCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_ExplicitDecodingConfig.AudioEncoding: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUDIO_ENCODING_UNSPECIFIED\0\u{1}LINEAR16\0\u{1}MULAW\0\u{1}ALAW\0")
}

extension Google_Cloud_Speech_V2_RecognitionConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RecognitionConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{7}auto_decoding_config\0\u{3}explicit_decoding_config\0\u{1}model\0\u{3}language_codes\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 7: try {
        var v: Google_Cloud_Speech_V2_AutoDetectDecodingConfig?
        var hadOneofValue = false
        if let current = self.decodingConfig {
          hadOneofValue = true
          if case .autoDecodingConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.decodingConfig = .autoDecodingConfig(v)
        }
      }()
      case 8: try {
        var v: Google_Cloud_Speech_V2_ExplicitDecodingConfig?
        var hadOneofValue = false
        if let current = self.decodingConfig {
          hadOneofValue = true
          if case .explicitDecodingConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.decodingConfig = .explicitDecodingConfig(v)
        }
      }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 10: try { try decoder.decodeRepeatedStringField(value: &self.languageCodes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.decodingConfig {
    case .autoDecodingConfig?: try {
      guard case .autoDecodingConfig(let v)? = self.decodingConfig else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .explicitDecodingConfig?: try {
      guard case .explicitDecodingConfig(let v)? = self.decodingConfig else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case nil: break
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 9)
    }
    if !self.languageCodes.isEmpty {
      try visitor.visitRepeatedStringField(value: self.languageCodes, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_RecognitionConfig, rhs: Google_Cloud_Speech_V2_RecognitionConfig) -> Bool {
    if lhs.decodingConfig != rhs.decodingConfig {return false}
    if lhs.model != rhs.model {return false}
    if lhs.languageCodes != rhs.languageCodes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_StreamingRecognitionFeatures: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StreamingRecognitionFeatures"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}enable_voice_activity_events\0\u{3}interim_results\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enableVoiceActivityEvents) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.interimResults) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enableVoiceActivityEvents != false {
      try visitor.visitSingularBoolField(value: self.enableVoiceActivityEvents, fieldNumber: 1)
    }
    if self.interimResults != false {
      try visitor.visitSingularBoolField(value: self.interimResults, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_StreamingRecognitionFeatures, rhs: Google_Cloud_Speech_V2_StreamingRecognitionFeatures) -> Bool {
    if lhs.enableVoiceActivityEvents != rhs.enableVoiceActivityEvents {return false}
    if lhs.interimResults != rhs.interimResults {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_StreamingRecognitionConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StreamingRecognitionConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}config\0\u{3}streaming_features\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._config) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._streamingFeatures) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._config {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._streamingFeatures {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_StreamingRecognitionConfig, rhs: Google_Cloud_Speech_V2_StreamingRecognitionConfig) -> Bool {
    if lhs._config != rhs._config {return false}
    if lhs._streamingFeatures != rhs._streamingFeatures {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_StreamingRecognizeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StreamingRecognizeRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{3}recognizer\0\u{2}\u{2}audio\0\u{3}streaming_config\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularStringField(value: &self.recognizer) }()
      case 5: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.streamingRequest != nil {try decoder.handleConflictingOneOf()}
          self.streamingRequest = .audio(v)
        }
      }()
      case 6: try {
        var v: Google_Cloud_Speech_V2_StreamingRecognitionConfig?
        var hadOneofValue = false
        if let current = self.streamingRequest {
          hadOneofValue = true
          if case .streamingConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.streamingRequest = .streamingConfig(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.recognizer.isEmpty {
      try visitor.visitSingularStringField(value: self.recognizer, fieldNumber: 3)
    }
    switch self.streamingRequest {
    case .audio?: try {
      guard case .audio(let v)? = self.streamingRequest else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
    }()
    case .streamingConfig?: try {
      guard case .streamingConfig(let v)? = self.streamingRequest else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_StreamingRecognizeRequest, rhs: Google_Cloud_Speech_V2_StreamingRecognizeRequest) -> Bool {
    if lhs.recognizer != rhs.recognizer {return false}
    if lhs.streamingRequest != rhs.streamingRequest {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_SpeechRecognitionAlternative: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SpeechRecognitionAlternative"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}transcript\0\u{1}confidence\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.transcript) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.confidence) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.transcript.isEmpty {
      try visitor.visitSingularStringField(value: self.transcript, fieldNumber: 1)
    }
    if self.confidence.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.confidence, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_SpeechRecognitionAlternative, rhs: Google_Cloud_Speech_V2_SpeechRecognitionAlternative) -> Bool {
    if lhs.transcript != rhs.transcript {return false}
    if lhs.confidence != rhs.confidence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_StreamingRecognitionResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StreamingRecognitionResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}alternatives\0\u{3}is_final\0\u{1}stability\0\u{4}\u{2}channel_tag\0\u{3}language_code\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.alternatives) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isFinal) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.stability) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.channelTag) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.languageCode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.alternatives.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.alternatives, fieldNumber: 1)
    }
    if self.isFinal != false {
      try visitor.visitSingularBoolField(value: self.isFinal, fieldNumber: 2)
    }
    if self.stability.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.stability, fieldNumber: 3)
    }
    if self.channelTag != 0 {
      try visitor.visitSingularInt32Field(value: self.channelTag, fieldNumber: 5)
    }
    if !self.languageCode.isEmpty {
      try visitor.visitSingularStringField(value: self.languageCode, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_StreamingRecognitionResult, rhs: Google_Cloud_Speech_V2_StreamingRecognitionResult) -> Bool {
    if lhs.alternatives != rhs.alternatives {return false}
    if lhs.isFinal != rhs.isFinal {return false}
    if lhs.stability != rhs.stability {return false}
    if lhs.channelTag != rhs.channelTag {return false}
    if lhs.languageCode != rhs.languageCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_StreamingRecognizeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StreamingRecognizeResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{3}speech_event_type\0\u{2}\u{3}results\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularEnumField(value: &self.speechEventType) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.results) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.speechEventType != .unspecified {
      try visitor.visitSingularEnumField(value: self.speechEventType, fieldNumber: 3)
    }
    if !self.results.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.results, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Cloud_Speech_V2_StreamingRecognizeResponse, rhs: Google_Cloud_Speech_V2_StreamingRecognizeResponse) -> Bool {
    if lhs.results != rhs.results {return false}
    if lhs.speechEventType != rhs.speechEventType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Cloud_Speech_V2_StreamingRecognizeResponse.SpeechEventType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SPEECH_EVENT_TYPE_UNSPECIFIED\0\u{1}END_OF_SINGLE_UTTERANCE\0\u{1}SPEECH_ACTIVITY_BEGIN\0\u{1}SPEECH_ACTIVITY_END\0")
}
